server:
  port: 7080
spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:/darakbang-3b7415068a92.json
        project-id: darakbang
        bucket: darakbang-img
  
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/post?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:mysql://localhost:3305/post?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password : 1234
  application:
    name: post-api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

