server:
  port: 7080
spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:/darakbang-3b7415068a92.json
        project-id: darakbang
        bucket: darakbang-img
  
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password : 1234
  application:
    name: product-api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
eureka:
  instance:

    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    transport:
      protocol: smtp
    debug: true
    default:
      encoding: UTF-8
    mime:
      charset: UTF-8
    username: dealon2580@gmail.com  
    password: asas1212!
